#include <iostream>
#include <fstream>
#include <string>

//Header file generated by protobuf
#include "Phone.pb.h"

using namespace std;

#define SPACER cout<<"==================================="<<endl

void takePersonInput(tutorial::User* user)
{
    //Function to accept user input which includes name, phone number and a list of messages
    //Stores information in tutorial::User object
    string name,number,msg;
    cout << "Enter the Person's name: " << endl;
    getline(cin, name);
    user->set_name(name);
    cout << "Enter the Person's phone number: " << endl;
    getline(cin, number);
    tutorial::PhoneNumber* num = new tutorial::PhoneNumber();
    
    num->set_number(number);
    user->set_allocated_phone(num);
    cout << "Enter the message you want to store: (LEAVE BLANK TO EXIT) " << endl;
    while (true)
    {
        cout << "> ";
        getline(cin, msg);
        if (msg.empty())
        {
            break;
        }
        tutorial::Notes* note = user->add_usernotes();
        note->set_text(msg);      
    }
    
    
}

void showPersonOutput(tutorial::UserTextList& userlist)
{
    //Function to display output of the recorded information
    //Outputs all the information that is present in the list of objects
    for (int i = 0; i < userlist.users_size();i++) {
        SPACER;
        tutorial::User u = userlist.users(i);
        cout << "Person Name: " << u.name()<<endl;
        tutorial::PhoneNumber num = u.phone();
        cout << "Phone number is: " << num.number() << endl;
        for (int j = 0; j < u.usernotes_size(); j++)
        {
            cout << "Note " << j + 1 << endl;
            cout << "----------------------------------" << endl;
            cout << u.usernotes(j).text() << endl;
            cout << "-------------------------------" << endl;

        }
        SPACER;
    }
}

int main()
{
   GOOGLE_PROTOBUF_VERIFY_VERSION;

    tutorial::UserTextList users;

    fstream fin,fout;

    //Opens existing file, creates new one if not present
    fin.open("Userbook", ios::in | ios::binary);
    if (!fin.is_open())
    {
        cout << "No such file exists... Creating new file" << endl;
    }
    //Reads the file, and parses information to a UserTextList object which is a collection of tutorial::User objects
    else if (!users.ParseFromIstream(&fin))
    {
        cout << "Failed to parse from file..." << endl;
        return -1;
    }
    fin.close();
    //Adds information about new user by passing an empty tutorial::User object to takePersonInput
    takePersonInput(users.add_users());
 
    //Writes new UserTextList object to the file
    fout.open("Userbook", ios::out | ios::trunc | ios::binary);
    if (!users.SerializeToOstream(&fout))
    {
        cout << "Failed to write to file" << endl;
        return -1;
    }
    fout.close();
    SPACER;

    cout << "Reading From File..." << endl;

    //Opens existing file
    fstream finn("Userbook", ios::in | ios::binary);
    if (!users.ParseFromIstream(&finn))
    {
        cout << "Failed to parse from file..." << endl;
    }

    //Shows all recorded information
    showPersonOutput(users);



    //Garbage collection
    google::protobuf::ShutdownProtobufLibrary();
    return 0;
}

